# Generated by Django 2.1.7 on 2019-03-12 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('is_completed', models.BooleanField(default=False)),
                ('city', models.ManyToManyField(blank=True, to='hire_app.City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hire_app.CompanyProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(blank=True, max_length=1000, null=True)),
                ('tagline', models.CharField(blank=True, max_length=300, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('main_link', models.URLField(blank=True, null=True)),
                ('secondary_link', models.URLField(blank=True, null=True)),
                ('work_experience_1', models.TextField(blank=True, null=True)),
                ('work_experience_2', models.TextField(blank=True, null=True)),
                ('work_experience_3', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('city', models.ManyToManyField(blank=True, to='hire_app.City')),
                ('skills', models.ManyToManyField(to='hire_app.Skills')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='interest',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hire_app.Position'),
        ),
        migrations.AddField(
            model_name='interest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
