# Generated by Django 2.1.7 on 2019-03-18 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hire_app', '0002_auto_20190312_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='pos',
            new_name='position',
        ),
        migrations.AddField(
            model_name='position',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
