# Generated by Django 2.1.7 on 2019-03-19 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hire_app', '0005_auto_20190318_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='positions',
        ),
        migrations.AddField(
            model_name='position',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hire_app.CompanyProfile'),
        ),
    ]
