# Generated by Django 2.1.7 on 2019-03-20 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hire_app', '0006_auto_20190319_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='position_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
