# Generated by Django 2.1.7 on 2019-03-20 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire_app', '0007_position_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='position_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
